---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  customize:
    cpus: 1
    memory: 512

platforms:
- name: ubuntu-12.04
  run_list: ['recipe[apt]']
  driver_config:
    box: opscode-ubuntu-12.04
- name: ubuntu-14.04
  run_list: ['recipe[apt]']
  driver_config:
    box: opscode-ubuntu-14.04

suites:
- name: default
  run_list: ['recipe[dns::default]']
  attributes:
    dns:
      provider: ""
      credentials: {}
- name: dme_api20
  run_list: ['recipe[dns-test::dme]']
  attributes:
    dns-test:
      access_key: <%= ENV['DME_API_KEY'] %>
      secret_key: <%= ENV['DME_SECRET_KEY'] %>
    dns:
      domain: <%= ENV['DME_DOMAIN'] %>
      entry:
        name: <%= ENV['DME_ENTRY_NAME'] %>
        value: '1.1.1.1'
        type: 'A'
        ttl: 600
